### ISSUE TITLE
Add QNX support for keyboard_handler

### ISSUE THREAD

**Issue by kjeromebb** [ros-tooling/keyboard_handler#14]
## Description

Blackberry QNX OS has its terminal interface header `termio.h` in the `/usr/include/sys` directory instead of `/usr/include` as it is on typical Linux systems. 

## Completion Criteria
Add support for building ros-tooling/keyboard_handler on QNX. keyboard_handler would build successfully on QNX after the completion of this issue.

## Implementation Notes / Suggestions
Implementation can be a simple `ifdef` in the area where `termios.h` is included, which is `keyboard_handler_unix_impl.hpp` in this repository.

Change line 19 of `keyboard_handler_unix_impl.hpp` from `#include <termios.h>` to the following. Note: `termio.h` already includes `termios.h`.
```
#ifdef __QNXNTO__
#include <sys/termio.h>
#else
#include <termios.h>
#endif
```

## Testing Notes / Suggestions
The preceding code has been tested on Ubuntu 20.04 and QNX710 respectively, building properly on both systems.

Co-authored with Jordan Mao @jmaobb

**Comment by emersonknapp** [comment]
The approach looks fine, a PR would be welcome :)

**Comment by MichaelOrlov** [comment]
@kjeromebb This is very strange. We do have QNX build on CI in Apex.AI and also using 
`#include <termios.h>` in `rosbag2_transport.cpp` and have no issues with compilation.  
However we are using **QNX700**
Does this issue specific for the **QNX710** version?

**Comment by kjeromebb** [comment]
Haven't been able to get this to build on QNX700 as there are a few other barriers to getting it to work on our side (specifically, linking regex). The differences between `termios.h` and `termio.h` on QNX700 versus on QNX710 seem to be negligible according to a diff. I'd like to say it's QNX710 specific but have no evidence for it being so.

Going to look into it a bit more.

**Comment by jmaobb** [comment]
The reason why our QNX builds are giving different results is likely because we are building `keyboard_handler` before `rosbag2_py`. 
When `keyboard_handler` gets built, the `#include <termios.h>` in it defines `_TERMIOS_H_INCLUDED`. 
Now when `rosbag2_py` gets built, it includes `qnx710/target/qnx7/usr/include/python3.8/pyport.h`, which contains:
```
/* On QNX 6, struct termio must be declared by including sys/termio.h
   if TCGETA, TCSETA, TCSETAW, or TCSETAF are used.  sys/termio.h must
   be included before termios.h or it will generate an error. */
#if defined(HAVE_SYS_TERMIO_H) && !defined(__hpux)
#include <sys/termio.h>
#endif
```
If we look inside `qnx710/target/qnx7/usr/include/sys/termio.h`, we can see that it has the structure:
```
#ifndef __TERMIO_H_INCLUDED
#define __TERMIO_H_INCLUDED

#ifndef _TERMIOS_H_INCLUDED
#include <termios.h>
...
#else
#error termio/termios incompatibility
#endif
...
#endif
```
Since `keyboard_handler` defined `_TERMIOS_H_INCLUDED` already, `rosbag2_py` results with `#error termio/termios incompatibility`.

**Comment by kjeromebb** [comment]
Closing this issue for now as it seems not to be rooted in this specific package.
