### ISSUE TITLE
Release into Rolling

### ISSUE THREAD

**Issue by clalancette** [ros-tooling/keyboard_handler#17]
There is one change in this package that we would like to get into Rolling: https://github.com/ros-tooling/keyboard_handler/pull/12 .  Could one of the maintainers here do a new release?  Alternatively, if you give me write permissions I can do the release for you.  Thanks in advance.

**Comment by emersonknapp** [comment]
@clalancette I have invited you to the org as an owner

**Comment by clalancette** [comment]
> @clalancette I have invited you to the org as an owner

Excellent, thanks @emersonknapp.  I've now done a new release, so I'll close this out.
