### ISSUE TITLE
Add ability to call SIGINT handler which has already been installed in the system before KeybordHandler 

### ISSUE THREAD

**Issue by MichaelOrlov** [ros-tooling/keyboard_handler#9]
## Description
We need to be able to preserve calling system `SIGINT` handler which has already been installed in the system before `KeybordHandler` constructor.

Currently `KeyboardHandler` overriding `SIGINT` signal on construction which cause a problem when trying to use `KeyboardHandler` alongside with `rclcpp` when interruption of the process by "CTRL+C" is expected to be handled by the `rclcpp`.

In particular it cause a problem when we are trying to use `KeybordHandler` to process `pause/resume` operations for `Rosbag2` recording started from command line. https://github.com/ros2/rosbag2/pull/905#issuecomment-964567795. Since `Rosbag2` imply to finish recording by pressing `CTRL+C` keys. 

## Related Issues
- Blocks https://github.com/ros2/rosbag2/pull/905

## Completion Criteria
If `KeyboardHandler` using alongside with `rclcpp` signal handler, `rclcpp` signal handler should be called after internal `KeyboardHandler` signal handler.

## Implementation Notes / Suggestions
Possible solution would be to store locally in `KeyboardHandler` previously settled up `SIGINT` handler and reinstall it and re-transmit `SIGINT` one more time after internally processing it. i.e. signal chaining.  

## Testing Notes / Suggestions
Consider to create unit test with installing `SIGINT` handler before creating `KeyboardHandler` instance then send `SIGINT` from another process to check that both `SIGINT` handlers will be calling.

**Comment by ivanpauno** [comment]
Currently, the `KeyboardHandler` signal handler installed by default is calling `exit()`.
In the case we want to apply signal chaining, it would be good if `exit()` isn't called when signal chaining happens.
`exit()` could be called if the previously installed signal handler is `SIG_DFL` (actually `_exit()` should be called, as `exit()` is not async signal safe).

The other alternative is to have an option to disable `KeyboardHandler` signal handling, and expose a method that the user can call from its own signal handler (in the case of an rclcpp/rclpy node, we can use an "on_shutdown" callback). In this case we actually only need an static method.
I think that option is more clean, I don't like libraries automatically installing signal handlers and not having an option to disable it (installing signal handlers without having control of the whole application can easily be problematic).

**Comment by MichaelOrlov** [comment]
@ivanpauno Thanks for your comment. I've got your point. I will try to implement solution with static `on_shutdown()` method first.
